

post https://sportilize.herokuapp.com/api/v1/events/create
Content-Type: application/json

{
    "creator":"creatorUUID",
    "participantsNumber":10,
    "location" : "geoCoords",
    "startDate":"unix timestamp",
	"endDate":"unix timestamp",
    "infrastructure" : 12334,
    "description": "This is a great event",
    "sports" : ["tennis","volleyball","badminton"]
  }